const q=id=>document.getElementById(id),read=(k,f)=>JSON.parse(localStorage.getItem(k)||JSON.stringify(f)),write=(k,v)=>localStorage.setItem(k,JSON.stringify(v));
setTimeout(()=>{const grid=document.querySelector('.feature-grid.expanded');if(grid&&!document.querySelector('[href="screen-reduction.html"]'))grid.insertAdjacentHTML('beforeend','<a class="feature-card breathe" href="screen-reduction.html"><span>Screen</span><div><small>DIGITAL WELLBEING</small><h2>Screen reduction</h2><p>Take focus breaks and protect your sleep.</p></div><b>→</b></a>')},0);
setTimeout(()=>{if(q('dashName')&&!q('preventionPlan'))document.querySelector('.dash-grid').insertAdjacentHTML('afterend','<section id="preventionPlan" class="prevention card"><p class="eyebrow">DEFAULT PREVENTION PLAN</p><h2>Six small habits that protect your wellbeing</h2><div><article><b>Screen time</b><span>Take a 20-second eye break every 20 minutes.</span></article><article><b>Sleep</b><span>Set a regular wind-down time and aim for 7–9 hours.</span></article><article><b>Exercise</b><span>Move for at least 20 minutes today.</span></article><article><b>Stress</b><span>Pause for one minute of slow breathing.</span></article><article><b>Nutrition</b><span>Choose a balanced meal with protein and colour.</span></article><article><b>Water</b><span>Work toward 6–8 glasses through the day.</span></article></div></section>')},0);
const account=()=>read('vwAccount',{name:'Pranav',email:'pranav@vitawell.app',password:'1234'});
if(q('createAccount'))q('createAccount').onsubmit=e=>{e.preventDefault();if(q('accountPassword').value!==q('confirmPassword').value)return alert('Passwords do not match.');write('vwAccount',{name:q('accountName').value,email:q('accountEmail').value,password:q('accountPassword').value});location.href='profile.html'};
if(q('secureLogin'))q('secureLogin').onsubmit=e=>{e.preventDefault();const a=account();if(q('loginEmail').value!==a.email||q('loginPassword').value!==a.password)return alert('Incorrect email or password.');location.href='health-default.html'};
if(q('wellnessProfile')){const p=read('vwProfile',{});['fullName','dob','gender','goal','country','state','district','phone','blood','height','weight','language','allergies','conditions','emergency'].forEach(k=>{if(q(k)&&p[k])q(k).value=p[k]});q('wellnessProfile').onsubmit=e=>{e.preventDefault();const d={};['fullName','dob','gender','goal','country','state','district','phone','blood','height','weight','language','allergies','conditions','emergency'].forEach(k=>d[k]=q(k).value);write('vwProfile',d);location.href='health-default.html'}};
function score(d){let s=50;s+=Math.max(0,20-Math.abs(d.sleep-8)*5);s+=Math.min(15,d.water*2);s+=Math.min(15,d.exercise/2);s+=(+d.mood)*3;s-=(+d.stress)*4;s+=+d.meals*2;s-=Math.max(0,d.screen-4)*2;return Math.max(0,Math.min(100,Math.round(s)))}
if(q('dailyCheck'))q('dailyCheck').onsubmit=e=>{e.preventDefault();const d={sleep:+q('sleepHours').value,water:+q('waterGlasses').value,exercise:+q('exerciseMinutes').value,mood:q('mood').value,stress:q('stress').value,screen:+q('screenTime').value,meals:q('meals').value,symptoms:q('symptoms').value,date:new Date().toLocaleDateString()};d.score=score(d);let h=read('vwChecks',[]);h.unshift(d);write('vwChecks',h);q('checkResult').classList.remove('hidden');q('resultScore').textContent=d.score;q('resultTitle').textContent=d.score>=75?'You are building a strong day.':d.score>=50?'A few small adjustments can help.':'Start with one kind, achievable step.';let tips=[];if(d.sleep<7)tips.push('Aim for a calmer wind-down and 7–9 hours of sleep.');if(d.water<6)tips.push('Keep a glass nearby and drink water regularly.');if(d.exercise<20)tips.push('Try a 10-minute walk or gentle stretch.');if(d.stress>1)tips.push('Take three slow breaths and a short screen-free pause.');if(d.screen>5)tips.push('Use the 20–20–20 rule for a screen break.');if(d.meals<3)tips.push('Plan one nourishing, balanced meal.');q('suggestionList').innerHTML=(tips.length?tips:['Keep repeating the habits that support you.']).map(x=>`<p>✓ ${x}</p>`).join('')};
if(q('dashName')){const p=read('vwProfile',{}),h=read('vwChecks',[]),d=h[0];q('dashName').textContent=(p.fullName||account().name).split(' ')[0];if(d){q('dashScore').textContent=d.score;q('dashScoreCaption').textContent=d.score>=75?'A balanced day so far':'Small changes can lift your score';[['sleepProgress','sleepVal',d.sleep,10,'h'],['waterProgress','waterVal',d.water,8,' glasses'],['moveProgress','moveVal',d.exercise,30,' min']].forEach(([bar,val,n,max,s])=>{q(bar).style.width=Math.min(100,n/max*100)+'%';q(val).textContent=n+s})}};
if(q('lastScore')){const h=read('vwChecks',[]);q('lastScore').textContent=h[0]?.score??'—';q('checkCount').textContent=h.length;q('weeklyAverage').textContent=h.length?Math.round(h.slice(0,7).reduce((a,x)=>a+x.score,0)/Math.min(7,h.length)):'—';q('historyList').innerHTML=h.length?h.slice(0,10).map(x=>`<div><span>${x.date}</span><b>${x.score}/100</b><small>${x.sleep}h sleep · ${x.water} glasses · ${x.exercise} min movement</small></div>`).join(''):q('historyList').innerHTML};
