const el=id=>document.getElementById(id);
const get=(key,fallback)=>{try{return JSON.parse(localStorage.getItem(key))||fallback}catch(_){return fallback}};
const put=(key,value)=>localStorage.setItem(key,JSON.stringify(value));
document.addEventListener('DOMContentLoaded',()=>{
  const showNotice=message=>{let notice=el('connectionNotice');if(!notice){notice=document.createElement('div');notice.id='connectionNotice';notice.className='connection-notice';document.body.append(notice)}notice.textContent=message|| (navigator.onLine?'Online — reminders are ready.':'Offline — reminders stay inside the app.');notice.classList.toggle('offline',!navigator.onLine)};
  showNotice();addEventListener('online',()=>showNotice());addEventListener('offline',()=>showNotice());window.VitaNotify=showNotice;
  const settingsForm=el('settingsForm');
  if(settingsForm){const settings=get('vwSettings',{goal:6000,water:true,tips:true});el('settingsGoal').value=settings.goal;el('settingsWater').checked=settings.water;el('settingsTips').checked=settings.tips;
    settingsForm.addEventListener('submit',event=>{event.preventDefault();put('vwSettings',{goal:+el('settingsGoal').value,water:el('settingsWater').checked,tips:el('settingsTips').checked});alert('Preferences saved.');});
    el('resetApp').addEventListener('click',()=>{if(confirm('Remove your VitaWell profile, preferences, and logged activity?')){Object.keys(localStorage).filter(key=>key.startsWith('vw')||key.startsWith('vitawell')).forEach(key=>localStorage.removeItem(key));location.href='index.html';}});
  }
  const newsForm=el('newsForm'),newsFeed=el('newsFeed');
  const renderNews=()=>{if(!newsFeed)return;const items=get('vwNews',[]);newsFeed.innerHTML=items.length?items.map((item,index)=>`<article class="news-item card"><small>${item.date}</small><h2>${item.title}</h2><p>${item.copy}</p><button data-delete="${index}" class="quiet-button">Remove</button></article>`).join(''):'<p class="empty-state">No updates yet. Open News Publisher to post the first update.</p>';newsFeed.querySelectorAll('[data-delete]').forEach(button=>button.onclick=()=>{const items=get('vwNews',[]);items.splice(+button.dataset.delete,1);put('vwNews',items);renderNews()});};
  if(newsForm)newsForm.addEventListener('submit',event=>{event.preventDefault();const title=el('newsTitle').value.trim(),copy=el('newsCopy').value.trim();if(!title||!copy)return;const items=get('vwNews',[]);items.unshift({title,copy,date:new Date().toLocaleString()});put('vwNews',items);newsForm.reset();location.href='news.html';});renderNews();
  if(el('stepsNow')){let steps=+(localStorage.getItem('vwSteps')||0),goal=get('vwSettings',{goal:6000}).goal||6000;const render=()=>{el('stepsNow').textContent=steps.toLocaleString();el('stepGoal').textContent=goal.toLocaleString();el('movementTitle').textContent=steps>=goal?'Goal reached — wonderful work!':`${Math.max(0,goal-steps).toLocaleString()} steps to your goal`;};document.querySelectorAll('[data-workout]').forEach(button=>button.onclick=()=>{steps+=+button.dataset.steps;localStorage.setItem('vwSteps',steps);render()});render();}
  if(el('addWater')){let count=+(localStorage.getItem('vwWater')||0);const render=()=>{el('waterCount').textContent=count;el('waterFill').style.height=Math.min(100,count/8*100)+'%';el('waterMessage').textContent=count>=8?'Daily hydration goal reached. Nicely done!':`${8-count} more glasses to reach your goal.`;el('addWater').disabled=count>=8};el('addWater').onclick=()=>{count++;localStorage.setItem('vwWater',count);render()};render();}
  if(el('wellnessSurvey'))el('wellnessSurvey').onsubmit=event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.target));put('vwSurvey',data);el('surveyResult').classList.remove('hidden');el('surveyTitle').textContent=data.mood==='Strained'?'A softer day is okay.':'You checked in with yourself.';};
  if(el('reportSteps')){const survey=get('vwSurvey',{}),steps=+(localStorage.getItem('vwSteps')||0),water=+(localStorage.getItem('vwWater')||0);el('reportSteps').textContent=steps.toLocaleString();el('reportWater').textContent=water;el('reportMood').textContent=survey.mood||'—';}
});
